# Generated by Django 4.1.7 on 2023-12-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
